

package org.dom4j.dtd;

import org.dom4j.AbstractTestCase;
import org.dom4j.DocTypeTest;

/**
 * Tests the {@link ElementDecl}functionality. Tests each of the property
 * access methods and the serialization mechanisms. Correct parsing is tested by
 * {@link DocTypeTest}.
 * 
 * <P>
 * </p>
 * 
 * @author Bryan Thompson
 * @author Maarten Coene
 * @version $Revision: 1.3 $
 * 
 * @todo The dom4j documentation needs to describe what representation SHOULD be
 *       generated by {@link ElementDecl#toString()}.
 */
public class ElementDeclTest extends AbstractTestCase {



    /**
     * Test
     * 
     * <pre>
     * 
     *  &lt;!ELEMENT an-element (#PCDATA)&gt;
     *  
     * </pre>
     */
    public void testSimpleElementDecl() {
        String expectedName = "an-element";

        String expectedModel = "(#PCDATA)";

        String expectedText = "<!ELEMENT an-element (#PCDATA)>";

        ElementDecl actual = new ElementDecl(expectedName, expectedModel);

        assertEquals("name is correct", expectedName, actual.getName());

        assertEquals("model is correct", expectedModel, actual.getModel());

        assertEquals("toString() is correct", expectedText, actual.toString());
    }

    // Implementation methods
    // -------------------------------------------------------------------------
}

