

package org.dom4j.dtd;

import org.dom4j.AbstractTestCase;
import org.dom4j.DocTypeTest;

/**
 * Tests the {@link ExternalEntityDecl}functionality. Tests each of the
 * property access methods and the serialization mechanisms. Correct parsing is
 * tested by {@link DocTypeTest}.
 * 
 * <P>
 * </p>
 * 
 * @author Bryan Thompson
 * @author Maarten Coene
 * @version $Revision: 1.3 $
 * 
 * @todo The dom4j documentation needs to describe what representation SHOULD be
 *       generated by {@link ExternalEntityDecl#toString()}.
 * @todo Test support for NOTATION and NDATA when used as part of an external
 *       entity declaration. dom4j does not appear to support NOTATION and NDATA
 *       at this time.
 */
public class ExternalEntityDeclTest extends AbstractTestCase {


    public void testToString() {
        ExternalEntityDecl decl1 = new ExternalEntityDecl("name", null,
                "systemID");
        ExternalEntityDecl decl2 = new ExternalEntityDecl("%name", null,
                "systemID");

        assertEquals("<!ENTITY name SYSTEM \"systemID\" >", decl1.toString());
        assertEquals("<!ENTITY % name SYSTEM \"systemID\" >", decl2.toString());
    }

    /**
     * Tests external entity declaration using only the SYSTEM identifier.
     */
    public void testSystemId() {
        String expectedName = "anEntity";

        String expectedPublicID = null;

        String expectedSystemID = "http://www.myorg.org/foo";

        String expectedText = "<!ENTITY anEntity "
                + "SYSTEM \"http://www.myorg.org/foo\" >";

        ExternalEntityDecl actual = new ExternalEntityDecl(expectedName,
                expectedPublicID, expectedSystemID);

        assertEquals("name is correct", expectedName, actual.getName());

        assertEquals("publicID is correct", expectedPublicID, actual
                .getPublicID());

        assertEquals("systemID is correct", expectedSystemID, actual
                .getSystemID());

        assertEquals("toString() is correct", expectedText, actual.toString());
    }

    /**
     * Tests external entity declaration using both SYSTEM and PUBLIC
     * identifiers.
     */
    public void testPublicIdSystemId() {
        String expectedName = "anEntity";

        String expectedPublicID = "-//dom4j//DTD sample";

        String expectedSystemID = "http://www.myorg.org/foo";

        String expectedText = "<!ENTITY anEntity "
                + "PUBLIC \"-//dom4j//DTD sample\" "
                + "\"http://www.myorg.org/foo\" >";

        ExternalEntityDecl actual = new ExternalEntityDecl(expectedName,
                expectedPublicID, expectedSystemID);

        assertEquals("name is correct", expectedName, actual.getName());

        assertEquals("publicID is correct", expectedPublicID, actual
                .getPublicID());

        assertEquals("systemID is correct", expectedSystemID, actual
                .getSystemID());

        assertEquals("toString() is correct", expectedText, actual.toString());
    }
}

